### ISSUE TITLE
several error in MinkowskiEngineBackend and in code

### ISSUE THREAD

**Issue by 4DVLab** [kumuji/mix3d#16]
* AttributeError: type object 'MinkowskiEngineBackend._C.RegionType' has no attribute 'HYBRID'
*     int_to_region_type = {m.value: m for m in ME.RegionType},TypeError: 'pybind11_type' object is not iterable

**Comment by kumuji** [comment]
You are trying to run code with the latest version of MinkowskiEngine. The codebase works with a version MinkowskiEngine v0.4.3, for a newer version you could use #11
